import type { PaperClosePreview } from "../types/database";

type PaperCloseConfirmationModalProps = { preview: PaperClosePreview; onCancel: () => void; onConfirm: () => void; loading: boolean; error: string | null };

function PaperCloseConfirmationModal({ preview, onCancel, onConfirm, loading, error }: PaperCloseConfirmationModalProps) {
  const pnlTone = preview.realized_pnl_estimate >= 0 ? "text-emerald-300" : "text-rose-300";
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/75 p-5 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="paper-close-confirmation-title"><section className="w-full max-w-md rounded-2xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-rose-200">Paper trading</p><h2 id="paper-close-confirmation-title" className="mt-2 text-xl font-semibold text-white">Confirm market close</h2><p className="mt-2 text-sm leading-6 text-slate-400">This closes the simulated position using the latest available quote. The final fill may differ if the quote changes before execution.</p><dl className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-lg border border-slate-800 bg-slate-950/70 p-3"><dt className="text-xs uppercase tracking-wide text-slate-500">Position</dt><dd className="mt-1 text-sm font-semibold text-white">{preview.ticker} · {preview.side}</dd></div><div className="rounded-lg border border-slate-800 bg-slate-950/70 p-3"><dt className="text-xs uppercase tracking-wide text-slate-500">Latest quote</dt><dd className="mt-1 text-sm font-semibold text-white">${preview.latest_quote.toFixed(2)}</dd></div><div className="rounded-lg border border-slate-800 bg-slate-950/70 p-3"><dt className="text-xs uppercase tracking-wide text-slate-500">Quote time</dt><dd className="mt-1 text-sm font-semibold text-white">{new Date(preview.quote_timestamp).toLocaleString()}</dd></div><div className="rounded-lg border border-slate-800 bg-slate-950/70 p-3"><dt className="text-xs uppercase tracking-wide text-slate-500">Estimated exit value</dt><dd className="mt-1 text-sm font-semibold text-white">${preview.estimated_exit_value.toFixed(2)}</dd></div><div className="col-span-2 rounded-lg border border-slate-800 bg-slate-950/70 p-3"><dt className="text-xs uppercase tracking-wide text-slate-500">Estimated realised P/L</dt><dd className={`mt-1 text-lg font-semibold ${pnlTone}`}>${preview.realized_pnl_estimate.toFixed(2)}</dd></div></dl>{error && <p className="mt-4 rounded-lg border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} disabled={loading} className="rounded-lg border border-slate-700 px-4 py-2 text-sm font-semibold text-slate-200 disabled:opacity-60">Cancel</button><button type="button" onClick={onConfirm} disabled={loading} className="rounded-lg bg-rose-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-60">{loading ? "Closing…" : "Close at Market"}</button></div></section></div>;
}

export default PaperCloseConfirmationModal;
