import type { TradePlan } from "../types/stock";

type PaperTradeConfirmationModalProps = { plan: TradePlan; onCancel: () => void; onConfirm: () => void; loading: boolean; error: string | null };

function PaperTradeConfirmationModal({ plan, onCancel, onConfirm, loading, error }: PaperTradeConfirmationModalProps) {
  const values = [["Ticker", plan.ticker], ["Side", "BUY"], ["Entry price", `$${plan.entry.toFixed(2)}`], ["Quantity", `${plan.position_size} shares`], ["Position value", `$${plan.total_position_value.toFixed(2)}`], ["Stop loss", `$${plan.stop_loss.toFixed(2)}`], ["Target 1", `$${plan.target_1.toFixed(2)}`], ["Target 2", `$${plan.target_2.toFixed(2)}`], ["Maximum risk", `$${plan.maximum_risk.toFixed(2)} (${plan.account_risk_percent.toFixed(2)}%)`], ["Confidence", `${plan.confidence_score}/100`], ["Target 1 R/R", `${plan.risk_reward_target_1.toFixed(2)}R`]];
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/75 p-5 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="paper-trade-confirmation-title"><section className="w-full max-w-lg rounded-2xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Paper trading</p><h2 id="paper-trade-confirmation-title" className="mt-2 text-xl font-semibold text-white">Confirm paper trade</h2><p className="mt-2 text-sm leading-6 text-slate-400">Review this simulated long position before it uses paper-trading cash.</p><dl className="mt-5 grid grid-cols-2 gap-3">{values.map(([label, value]) => <div key={label} className="rounded-lg border border-slate-800 bg-slate-950/70 p-3"><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-100">{value}</dd></div>)}</dl><p className="mt-5 rounded-lg border border-amber-400/20 bg-amber-400/10 p-3 text-xs leading-5 text-amber-100">Stops and targets are reference levels only and are not automatically executed.</p>{error && <p className="mt-4 rounded-lg border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} disabled={loading} className="rounded-lg border border-slate-700 px-4 py-2 text-sm font-semibold text-slate-200 disabled:opacity-60">Cancel</button><button type="button" onClick={onConfirm} disabled={loading} className="rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-60">{loading ? "Opening…" : "Confirm Paper Trade"}</button></div></section></div>;
}

export default PaperTradeConfirmationModal;
