import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import Header from "../components/Header";
import PaperCloseConfirmationModal from "../components/PaperCloseConfirmationModal";
import Sidebar, { type AppPage } from "../components/Sidebar";
import { userApi } from "../services/userApi";
import type { PaperClosePreview, PaperPortfolio, PaperTrade } from "../types/database";

type Props = { onNavigate: (page: AppPage) => void };
type Filters = { search: string; strategy: string; result: string; status: string; tag: string; grade: string; setup: string; from: string; to: string };
const blank: Filters = { search: "", strategy: "", result: "", status: "", tag: "", grade: "", setup: "", from: "", to: "" };
const money = (v = 0) => new Intl.NumberFormat(undefined, { style: "currency", currency: "USD" }).format(v);
const allTags = (t: PaperTrade) => [...(t.setup_tags ?? []), ...(t.mistake_tags ?? []), ...(t.emotion_tags ?? [])];
const coachGrade = (t: PaperTrade) => String(t.coach_analysis?.grade ?? "—");
const holding = (t: PaperTrade) => { const m = t.holding_minutes ?? Math.max(0, (Date.parse(t.closed_at ?? new Date().toISOString()) - Date.parse(t.opened_at)) / 60000); return m >= 1440 ? `${(m / 1440).toFixed(1)}d` : m >= 60 ? `${(m / 60).toFixed(1)}h` : `${Math.round(m)}m`; };
function filterJournalTrades(rows: PaperTrade[], f: Filters) { return rows.filter((t) => { const pnl = t.realized_pnl ?? t.unrealized_pnl ?? 0; const day = t.opened_at.slice(0, 10); return (!f.search || t.ticker.toLowerCase().includes(f.search.toLowerCase())) && (!f.strategy || t.recommendation.toLowerCase().includes(f.strategy.toLowerCase())) && (!f.result || (f.result === "win" ? pnl > 0 : f.result === "loss" ? pnl < 0 : pnl === 0)) && (!f.status || t.status === f.status) && (!f.tag || allTags(t).some((x) => x.toLowerCase().includes(f.tag.toLowerCase()))) && (!f.grade || coachGrade(t) === f.grade) && (!f.setup || (t.setup_quality ?? "").toLowerCase().includes(f.setup.toLowerCase())) && (!f.from || day >= f.from) && (!f.to || day <= f.to); }); }
function safeCsvValue(value: unknown) {
  const raw = String(value ?? "");
  const neutralized = /^[\t\r ]*[=+\-@]/.test(raw) ? `'${raw}` : raw;
  return `"${neutralized.replaceAll('"', '""')}"`;
}
function exportTradesCsv(name: string, rows: PaperTrade[]) { const heads = ["ticker", "side", "status", "entry", "current_or_exit", "quantity", "stop", "tp1", "tp2", "pnl", "r", "opened_at", "closed_at", "strategy", "coach_grade", "review_completed", "notes", "setup_tags", "mistake_tags", "emotion_tags", "lessons", "reference_url"]; const data = rows.map((t) => [t.ticker, t.side, t.status, t.entry_price, t.market_price ?? t.exit_price, t.quantity, t.stop_loss, t.target_1, t.target_2, t.realized_pnl ?? t.unrealized_pnl, t.realized_rr ?? t.unrealized_r, t.opened_at, t.closed_at, t.recommendation, coachGrade(t), t.review_completed, t.journal_notes, (t.setup_tags ?? []).join("|"), (t.mistake_tags ?? []).join("|"), (t.emotion_tags ?? []).join("|"), t.lessons_learned, t.screenshot_url]); const url = URL.createObjectURL(new Blob([[heads, ...data].map((r) => r.map(safeCsvValue).join(",")).join("\n")], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function Filters({ value: f, set }: { value: Filters; set: (f: Filters) => void }) { const c = "rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"; return <section className="rounded-xl border border-slate-800 bg-slate-900/40 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Ticker" className={c} placeholder="Ticker search" value={f.search} onChange={(e) => set({ ...f, search: e.target.value })}/><input aria-label="Strategy" className={c} placeholder="Strategy" value={f.strategy} onChange={(e) => set({ ...f, strategy: e.target.value })}/><select aria-label="Result" className={c} value={f.result} onChange={(e) => set({ ...f, result: e.target.value })}><option value="">All results</option><option value="win">Wins</option><option value="loss">Losses</option><option value="flat">Flat</option></select><select aria-label="Status" className={c} value={f.status} onChange={(e) => set({ ...f, status: e.target.value })}><option value="">Open and closed</option><option value="OPEN">Open</option><option value="CLOSED">Closed</option></select><input aria-label="Tag" className={c} placeholder="Tag" value={f.tag} onChange={(e) => set({ ...f, tag: e.target.value })}/><select aria-label="Coach grade" className={c} value={f.grade} onChange={(e) => set({ ...f, grade: e.target.value })}><option value="">All Coach grades</option>{["A","B","C","D","F"].map((x)=><option key={x}>{x}</option>)}</select><input aria-label="Setup" className={c} placeholder="Setup type" value={f.setup} onChange={(e) => set({ ...f, setup: e.target.value })}/><div className="flex gap-2"><input aria-label="From" type="date" className={`${c} min-w-0`} value={f.from} onChange={(e) => set({ ...f, from: e.target.value })}/><input aria-label="To" type="date" className={`${c} min-w-0`} value={f.to} onChange={(e) => set({ ...f, to: e.target.value })}/></div></div><button className="mt-3 text-xs text-cyan-300" onClick={() => set(blank)}>Clear filters</button></section>; }

export default function PaperTradingPage({ onNavigate }: Props) {
  const navigate = useNavigate(); const [portfolio, setPortfolio] = useState<PaperPortfolio | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const [filters, setFilters] = useState(blank); const [preview, setPreview] = useState<PaperClosePreview | null>(null); const [previewing, setPreviewing] = useState<string | null>(null); const [closing, setClosing] = useState(false);
  async function refresh(initial = false) { if (initial) setLoading(true); else setRefreshing(true); setError(null); try { setPortfolio(await userApi.paperPortfolio() as PaperPortfolio); } catch { setError("We couldn’t refresh the journal. Your last valid data is still shown."); } finally { setLoading(false); setRefreshing(false); } }
  useEffect(() => { void refresh(true); }, []);
  async function closePreview(t: PaperTrade) { setPreviewing(t.id); try { setPreview(await userApi.paperTradeClosePreview(t.id) as PaperClosePreview); } catch { setError("The close estimate is unavailable. The position remains unchanged."); } finally { setPreviewing(null); } }
  async function confirm() { if (!preview) return; setClosing(true); try { await userApi.closePaperTrade(preview.trade_id); setPreview(null); await refresh(); } catch { setError("The position could not be closed. It remains open."); } finally { setClosing(false); } }
  const rows = useMemo(() => filterJournalTrades([...(portfolio?.open_positions ?? []), ...(portfolio?.closed_positions ?? [])], filters), [portfolio, filters]); const open = rows.filter((t) => t.status === "OPEN"); const closed = rows.filter((t) => t.status === "CLOSED"); const risk = portfolio?.portfolio_risk;
  const metrics = portfolio && risk ? [["Account equity", money(portfolio.portfolio_balance)],["Available cash",money(portfolio.cash_balance)],["Open-position value",money(portfolio.open_position_value)],["Realised P/L",money(portfolio.realized_pnl)],["Unrealised P/L",money(portfolio.unrealized_pnl)],["Total open risk",`${risk.open_risk_r.toFixed(2)}R · ${money(risk.open_risk_currency)}`],["Daily risk used",`${risk.daily_new_risk_used_r.toFixed(2)}R`],["Remaining capacity",`${risk.remaining_daily_risk_budget_r.toFixed(2)}R today`],["Drawdown",`${money(risk.current_drawdown)} · ${risk.current_drawdown_r.toFixed(2)}R`],["Peak equity",money(risk.peak_equity)],["Risk status",risk.risk_status]] : [];
  return <div className="min-h-screen bg-slate-950 text-slate-100 lg:flex"><Sidebar activePage="paper-trading" onNavigate={onNavigate}/><div className="min-w-0 flex-1"><Header eyebrow="Paper trading only" title="Portfolio journal"/><main className="mx-auto max-w-[100rem] space-y-6 p-4 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-slate-400">Portfolio, trade history, Coach and personal review in one workspace.</p><p className="text-xs text-amber-200">Stops and targets remain reference levels. No real-money execution.</p></div><div className="flex gap-2"><button className="rounded-lg border border-slate-700 px-3 py-2 text-sm" onClick={() => exportTradesCsv("full-journal.csv", rows)}>Export journal</button><button className="rounded-lg border border-cyan-400/40 px-3 py-2 text-sm text-cyan-300" disabled={refreshing} onClick={() => void refresh()}>{refreshing?"Refreshing…":"Refresh"}</button></div></div>
  {error&&<div className="flex justify-between rounded-lg border border-amber-400/20 bg-amber-400/10 p-4 text-sm"><span>{error}</span><button className="underline" onClick={()=>void refresh()}>Retry</button></div>}{loading&&!portfolio?<div className="rounded-xl border border-slate-800 p-8 text-slate-400">Loading journal workspace…</div>:portfolio&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">{metrics.map(([a,b])=><div key={a} className="rounded-xl border border-slate-800 bg-slate-900/40 p-4"><p className="text-xs uppercase text-slate-500">{a}</p><p className="mt-2 font-semibold">{b}</p></div>)}</section><Filters value={filters} set={setFilters}/>
  <section className="rounded-xl border border-slate-800 bg-slate-900/40"><header className="flex justify-between border-b border-slate-800 p-5"><div><h2 className="font-semibold">Open positions</h2><p className="text-sm text-slate-500">Latest quotes and stored plans.</p></div><button className="text-xs text-cyan-300" onClick={()=>exportTradesCsv("open-positions.csv",open)}>Export CSV</button></header><div className="grid gap-3 p-4 xl:grid-cols-2">{open.map((t)=><article key={t.id} className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><div className="flex justify-between"><div><h3 className="font-semibold">{t.ticker} <span className="text-xs text-slate-500">{t.side}</span></h3><p className="text-xs text-slate-500">{t.recommendation} · {t.setup_quality??"Setup pending"} · {holding(t)}</p></div><p className={(t.unrealized_pnl??0)>=0?"text-emerald-300":"text-rose-300"}>{money(t.unrealized_pnl)} · {(t.unrealized_r??0).toFixed(2)}R</p></div><dl className="mt-4 grid grid-cols-3 gap-3 text-xs"><div><dt className="text-slate-500">Entry / current</dt><dd>{money(t.entry_price)} / {money(t.market_price)}</dd></div><div><dt className="text-slate-500">Quantity</dt><dd>{t.quantity}</dd></div><div><dt className="text-slate-500">Open risk</dt><dd>{(t.remaining_risk_r??t.initial_risk_r??0).toFixed(2)}R · {money(t.initial_risk_amount)}</dd></div><div><dt className="text-slate-500">Stop</dt><dd>{money(t.stop_loss)}</dd></div><div><dt className="text-slate-500">TP1 / TP2</dt><dd>{money(t.target_1)} / {money(t.target_2)}</dd></div><div><dt className="text-slate-500">Quote time</dt><dd>{t.latest_quote_timestamp?new Date(t.latest_quote_timestamp).toLocaleString():"Latest available"}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2"><button className="rounded-lg bg-cyan-400 px-3 py-2 text-xs font-semibold text-slate-950" onClick={()=>navigate(`/journal/${t.id}`)}>Open workspace</button><button className="rounded-lg border border-slate-700 px-3 py-2 text-xs" onClick={()=>navigate(`/journal/${t.id}#plan`)}>Review plan</button><button className="rounded-lg border border-slate-700 px-3 py-2 text-xs" onClick={()=>navigate(`/journal/${t.id}#notes`)}>Add note</button><button className="rounded-lg border border-rose-400/40 px-3 py-2 text-xs text-rose-200" disabled={previewing===t.id} onClick={()=>void closePreview(t)}>{previewing===t.id?"Checking…":"Close"}</button></div></article>)}{!open.length&&<p className="col-span-full py-10 text-center text-sm text-slate-500">No open positions match. Open paper trades from a validated trade plan.</p>}</div></section>
  <section className="rounded-xl border border-slate-800 bg-slate-900/40"><header className="flex justify-between border-b border-slate-800 p-5"><div><h2 className="font-semibold">Closed trades</h2><p className="text-sm text-slate-500">Coach output and review progress.</p></div><button className="text-xs text-cyan-300" onClick={()=>exportTradesCsv("closed-positions.csv",closed)}>Export CSV</button></header><div className="overflow-x-auto"><table className="w-full min-w-[75rem] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{["Ticker","Entry / exit","P/L","R","Holding","Exit reason","Strategy","Coach","Review","Actions"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{closed.map(t=><tr key={t.id} className="border-t border-slate-800"><td className="px-4 py-4 font-semibold">{t.ticker}</td><td className="px-4">{money(t.entry_price)} / {money(t.exit_price??0)}</td><td className={`px-4 ${(t.realized_pnl??0)>=0?"text-emerald-300":"text-rose-300"}`}>{money(t.realized_pnl??0)}</td><td className="px-4">{(t.realized_rr??0).toFixed(2)}R</td><td className="px-4">{holding(t)}</td><td className="px-4">{t.exit_reason??"Closed at market"}</td><td className="px-4">{t.recommendation}</td><td className="px-4">{coachGrade(t)}</td><td className="px-4">{t.review_completed?"Complete":"Needs review"}</td><td className="px-4"><div className="flex gap-2"><button className="text-cyan-300" onClick={()=>navigate(`/journal/${t.id}#coach`)}>Coach</button><button className="text-cyan-300" onClick={()=>navigate(`/workspace/${t.ticker}`)}>Chart</button><button className="text-cyan-300" onClick={()=>navigate(`/journal/${t.id}#notes`)}>Notes/tags</button><button className="text-cyan-300" onClick={()=>exportTradesCsv(`${t.ticker}.csv`,[t])}>Export</button></div></td></tr>)}{!closed.length&&<tr><td colSpan={10} className="py-10 text-center text-slate-500">No closed trades match these filters.</td></tr>}</tbody></table></div></section></>}</main></div>{preview&&<PaperCloseConfirmationModal preview={preview} loading={closing} error={null} onCancel={()=>setPreview(null)} onConfirm={()=>void confirm()}/>}</div>;
}
