import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { userApi } from "../services/userApi";
import type { PaperTrade } from "../types/database";
const money=(v=0)=>`$${v.toFixed(2)}`; const tagList=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
export default function TradeReviewPage({tradeId}:{tradeId:string}) {
 const navigate=useNavigate(); const [trade,setTrade]=useState<PaperTrade|null>(null); const [draft,setDraft]=useState<Partial<PaperTrade>>({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 useEffect(()=>{void(async()=>{try{const row=await userApi.paperTrade(tradeId) as PaperTrade;setTrade(row);setDraft(row);}catch{setMessage("This review is unavailable or does not belong to your account.");}finally{setLoading(false);}})();},[tradeId]);
 async function save(){setSaving(true);setMessage(null);try{const row=await userApi.updatePaperTradeJournal(tradeId,{journal_notes:draft.journal_notes||null,setup_tags:draft.setup_tags??[],mistake_tags:draft.mistake_tags??[],emotion_tags:draft.emotion_tags??[],confidence_before:draft.confidence_before??null,confidence_after:draft.confidence_after??null,screenshot_url:draft.screenshot_url||null,lessons_learned:draft.lessons_learned||null,review_completed:Boolean(draft.review_completed)}) as PaperTrade;setTrade(row);setDraft(row);setMessage("Review saved.");}catch{setMessage("Your review could not be saved. Your draft remains here; please retry.");}finally{setSaving(false);}}
 if(loading)return <main className="min-h-screen bg-slate-950 p-8 text-slate-400">Loading unified trade review…</main>; if(!trade)return <main className="min-h-screen bg-slate-950 p-8 text-rose-200">{message} <button className="underline" onClick={()=>navigate("/paper-trading")}>Return to journal</button></main>;
 const coach=trade.coach_analysis??{}; const field="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white";
 return <main className="min-h-screen bg-slate-950 p-4 text-slate-100 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><button className="text-sm text-cyan-300" onClick={()=>navigate("/paper-trading")}>← Portfolio journal</button><h1 className="mt-2 text-3xl font-semibold">{trade.ticker} trade review</h1><p className="text-sm text-slate-500">{trade.status} · {trade.side} · {trade.recommendation}</p></div><button className="rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-slate-950" disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save review"}</button></header>{message&&<p className="rounded-lg border border-cyan-400/20 bg-cyan-400/10 p-3">{message}</p>}
 <section id="plan" className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900/40 p-5 sm:grid-cols-3 lg:grid-cols-6">{[["Entry",money(trade.entry_price)],["Stop",money(trade.stop_loss)],["TP1",money(trade.target_1)],["TP2",money(trade.target_2)],["Exit",trade.exit_price?money(trade.exit_price):"Open"],["Result",trade.status==="CLOSED"?`${money(trade.realized_pnl??0)} · ${(trade.realized_rr??0).toFixed(2)}R`:`${money(trade.unrealized_pnl??0)} · ${(trade.unrealized_r??0).toFixed(2)}R`]].map(([a,b])=><div key={a}><p className="text-xs uppercase text-slate-500">{a}</p><p className="mt-1 font-semibold">{b}</p></div>)}</section>
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="font-semibold">Chart and evidence</h2><p className="mt-2 text-sm text-slate-400">Review the market chart beside the preserved plan and exits.</p><button className="mt-4 rounded-lg border border-cyan-400/40 px-3 py-2 text-sm text-cyan-300" onClick={()=>navigate(`/workspace/${trade.ticker}`)}>Open {trade.ticker} chart</button>{trade.screenshot_url&&<a className="ml-3 text-sm text-cyan-300 underline" href={trade.screenshot_url} target="_blank" rel="noreferrer">Open reference</a>}</div><div id="coach" className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="font-semibold">Coach output</h2>{Object.keys(coach).length?<div className="mt-3 space-y-2 text-sm text-slate-300"><p><b>Grade:</b> {String(coach.grade??"—")} · <b>Score:</b> {String(coach.score??"—")}</p><p>{String(coach.summary??"")}</p><p><b>Positives:</b> {Array.isArray(coach.positives)?coach.positives.join(" · "):"—"}</p><p><b>Improvements:</b> {Array.isArray(coach.improvements)?coach.improvements.join(" · "):"—"}</p></div>:<p className="mt-3 text-sm text-slate-500">Coach output is generated after close.</p>}</div></section>
 <section id="notes" className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="font-semibold">Journal and learning</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm">Notes<textarea className={field} rows={5} value={draft.journal_notes??""} onChange={e=>setDraft({...draft,journal_notes:e.target.value})}/></label>{([["Setup tags","setup_tags"],["Mistake tags","mistake_tags"],["Emotion tags","emotion_tags"]] as const).map(([label,key])=><label key={key} className="text-sm">{label}<input className={field} placeholder="Comma separated" value={(draft[key]??[]).join(", ")} onChange={e=>setDraft({...draft,[key]:tagList(e.target.value)})}/></label>)}<label className="text-sm">Confidence before<input type="number" min="0" max="100" className={field} value={draft.confidence_before??""} onChange={e=>setDraft({...draft,confidence_before:e.target.value?Number(e.target.value):null})}/></label><label className="text-sm">Confidence after<input type="number" min="0" max="100" className={field} value={draft.confidence_after??""} onChange={e=>setDraft({...draft,confidence_after:e.target.value?Number(e.target.value):null})}/></label><label className="sm:col-span-2 text-sm">Screenshot / reference URL<input type="url" className={field} value={draft.screenshot_url??""} onChange={e=>setDraft({...draft,screenshot_url:e.target.value})}/></label><label className="sm:col-span-2 text-sm">Lessons learned<textarea rows={4} className={field} value={draft.lessons_learned??""} onChange={e=>setDraft({...draft,lessons_learned:e.target.value})}/></label><label className="sm:col-span-2 flex gap-2 text-sm"><input type="checkbox" checked={Boolean(draft.review_completed)} onChange={e=>setDraft({...draft,review_completed:e.target.checked})}/> Review completed</label></div></section>
 <section className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="font-semibold">Learning insights</h2><p className="mt-2 text-sm text-slate-400">{trade.lessons_learned||String(coach.summary??"Compare execution, evidence and Coach feedback, then record the lesson above.")}</p></section></div></main>;
}
