import { useEffect, useState } from "react";

import Header from "../components/Header";
import Sidebar, { type AppPage } from "../components/Sidebar";
import { getValidationDashboard } from "../services/api";
import type { ValidationDashboard } from "../types/stock";

function ValidationPage({ onNavigate }: { onNavigate: (page: AppPage) => void }) {
  const [data, setData] = useState<ValidationDashboard | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  async function refresh() { setLoading(true); setError(null); try { setData(await getValidationDashboard()); } catch { setError("Validation metrics are unavailable right now. Please try again."); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  const cards = data ? [["Overall accuracy", `${data.overall_accuracy.toFixed(1)}%`], ["BUY accuracy", `${data.buy_accuracy.toFixed(1)}%`], ["WATCH accuracy", `${data.watch_accuracy.toFixed(1)}%`], ["STRONG BUY accuracy", `${data.strong_buy_accuracy.toFixed(1)}%`], ["Expected value", `${data.expected_value.toFixed(2)}R`], ["Measured observations", String(data.evaluated_observations)]] : [];
  return <div className="min-h-screen bg-slate-950 font-sans text-slate-100 lg:flex"><Sidebar activePage="validation" onNavigate={onNavigate} /><div className="min-w-0 flex-1"><Header eyebrow="Measured recommendations" title="AI Accuracy" /><main className="mx-auto max-w-7xl p-5 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><p className="max-w-2xl text-sm leading-6 text-slate-400">Every recorded recommendation is evaluated after 1, 3, 7, 14, and 30 days using its original entry, stop, and target.</p><button type="button" onClick={() => void refresh()} disabled={loading} className="rounded-lg border border-cyan-400/40 px-3 py-2 text-sm font-semibold text-cyan-300 disabled:opacity-60">{loading ? "Refreshing…" : "Refresh metrics"}</button></div>{error && <p className="mt-5 rounded-lg border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</p>}{loading && !data ? <div className="mt-6 rounded-xl border border-slate-800 bg-slate-900/40 p-6 text-sm text-slate-400">Evaluating recorded recommendations…</div> : data && <><section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>)}</section><section className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="font-semibold text-white">Confidence accuracy</h2><div className="mt-4 space-y-3">{Object.entries(data.confidence_accuracy).map(([range, accuracy]) => <div key={range} className="flex items-center justify-between rounded-lg bg-slate-950/60 px-3 py-3 text-sm"><span className="text-slate-400">{range}</span><span className="font-semibold text-white">{accuracy.toFixed(1)}%</span></div>)}</div></div><div className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="font-semibold text-white">Market regime</h2><div className="mt-4 space-y-3 text-sm"><p className="rounded-lg bg-emerald-400/5 p-3 text-emerald-100">Best: {data.best_market_regime.regime ?? "No measured regime"} · {data.best_market_regime.accuracy.toFixed(1)}%</p><p className="rounded-lg bg-rose-400/5 p-3 text-rose-100">Worst: {data.worst_market_regime.regime ?? "No measured regime"} · {data.worst_market_regime.accuracy.toFixed(1)}%</p><p className="text-slate-500">{data.tracked_recommendations} recommendations are being tracked.</p></div></div></section></>}</main></div></div>;
}

export default ValidationPage;
