"""Compatibility exports for the frozen swing-trading implementation."""

from strategies.swing_strategy import (
    APPROVAL_MAX_DRAWDOWN_R,
    APPROVAL_MIN_TRADES,
    ENTRY_WAIT,
    MAX_HOLDING_DAYS,
    MAX_RISK_PCT,
    SLIPPAGE_BPS,
    STOP_ATR,
    STRATEGY_METADATA,
    STRATEGY_VERSION,
    TARGET_1_R,
    TARGET_2_R,
    TP1_PORTION,
    TRANSACTION_COST_BPS,
    build_dashboard,
    build_live_signal,
    evaluate_signal,
    swing_trading_strategy,
)

__all__ = [
    "APPROVAL_MAX_DRAWDOWN_R",
    "APPROVAL_MIN_TRADES",
    "ENTRY_WAIT",
    "MAX_HOLDING_DAYS",
    "MAX_RISK_PCT",
    "SLIPPAGE_BPS",
    "STOP_ATR",
    "STRATEGY_METADATA",
    "STRATEGY_VERSION",
    "TARGET_1_R",
    "TARGET_2_R",
    "TP1_PORTION",
    "TRANSACTION_COST_BPS",
    "build_dashboard",
    "build_live_signal",
    "evaluate_signal",
    "swing_trading_strategy",
]
